//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressCorporate
    {
        public int addressCorporate_ID { get; set; }
        public Nullable<int> owner_ID { get; set; }
        public int addressType { get; set; }
        public bool primaryAddress { get; set; }
        public bool invoiceAddress { get; set; }
        public bool mailingAddress { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string suburb { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string department { get; set; }
        public string phoneNumber { get; set; }
        public string faxNumber { get; set; }
        public string email { get; set; }
        public string webSite { get; set; }
        public string ABN { get; set; }
        public string ACN { get; set; }
        public string contactTitle { get; set; }
        public string contactFirstname { get; set; }
        public string contactSurname { get; set; }
        public string subCompanyName { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
