//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalConsumption
    {
        public int UsedId { get; set; }
        public string RemotePatient_ID { get; set; }
        public long container_ID { get; set; }
        public string Name { get; set; }
        public int ProductId { get; set; }
        public string SPC { get; set; }
        public string Manufacturer { get; set; }
        public int patient_ID { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public string StaffName { get; set; }
        public string RebateCode { get; set; }
        public Nullable<decimal> MinBenefit { get; set; }
    }
}
