//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.AddressCorporates = new HashSet<AddressCorporate>();
        }
    
        public int company_ID { get; set; }
        public string companyName { get; set; }
        public string companyABN { get; set; }
        public string companyACN { get; set; }
        public string companyPhone { get; set; }
        public string companyFax { get; set; }
        public Nullable<int> note_ID { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> deletionReason { get; set; }
        public Nullable<int> deletionNote { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public string invoiceToUse { get; set; }
        public bool billing_Practice { get; set; }
        public bool billing_Scheduled { get; set; }
        public bool billing_Medicare { get; set; }
        public bool billing_HealthFund { get; set; }
        public bool billing_Other { get; set; }
        public Nullable<int> feeTable_ID { get; set; }
        public bool gapCover { get; set; }
        public string coversheetPrintSet { get; set; }
        public string chequeBSB { get; set; }
        public string healthFundType { get; set; }
        public string OnlineFundCode { get; set; }
        public string HL7MappingID { get; set; }
        public Nullable<System.DateTime> OnlineRecordUpdated { get; set; }
        public bool OnlineRegistered { get; set; }
        public bool OnlineActivated { get; set; }
        public Nullable<int> HMS_HealthfundReference { get; set; }
        public Nullable<int> Feed_ID { get; set; }
        public bool Requires_PracticeID { get; set; }
        public string OnlineContactPhone { get; set; }
        public string OnlineChangeReport { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string ExtCompany_ID { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<AddressCorporate> AddressCorporates { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
