//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumptionNotificationManagement
    {
        public ConsumptionNotificationManagement()
        {
            this.OrderItemSources = new HashSet<OrderItemSource>();
        }
    
        public int invUsed_ID { get; set; }
        public bool Invoiced { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public bool Reported { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
        public string ReportedBy { get; set; }
        public HMS.HealthTrack.Web.Data.Model.ConsumptionProcessingStatus ProcessingStatus { get; set; }
        public string ProcessingStatusMessage { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual ICollection<OrderItemSource> OrderItemSources { get; set; }
    }
}
