//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumptionManagement
    {
        public long ConsumptionId { get; set; }
        public bool Invoiced { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public bool Reported { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
        public string ReportedBy { get; set; }
        public int ProcessingStatus { get; set; }
        public string ProcessingStatusMessage { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
    
        public virtual Consumption Consumption { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
