//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeductionRequiringPaymentClass
    {
        public long StockAdjustmentId { get; set; }
        public long StockId { get; set; }
        public Nullable<System.DateTime> AdjustedOn { get; set; }
        public string AdjustedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        public string SPC { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> PrimarySupplier { get; set; }
        public Nullable<int> SecondarySupplier { get; set; }
        public bool IsConsignment { get; set; }
        public int MinimumOrder { get; set; }
        public int OrderMultiple { get; set; }
        public Nullable<int> ReorderThreshold { get; set; }
        public Nullable<int> TargetStockLevel { get; set; }
        public int patient_ID { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string mrn { get; set; }
        public Nullable<int> patientType { get; set; }
        public string homePhone { get; set; }
        public string workPhone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string pStatus { get; set; }
        public string medicare { get; set; }
        public string medicareRefNo { get; set; }
        public Nullable<int> MediExpYYYY { get; set; }
        public Nullable<byte> MediExpMM { get; set; }
        public Nullable<System.DateTime> medicareVerifyDate { get; set; }
        public string vetAffairs { get; set; }
        public Nullable<int> healthFundID { get; set; }
        public string fundNumber { get; set; }
        public string fundNumberUPI { get; set; }
        public Nullable<int> fundExpYYYY { get; set; }
        public Nullable<byte> fundExpMM { get; set; }
        public Nullable<int> fundPlan { get; set; }
        public Nullable<int> feeTable_ID { get; set; }
        public Nullable<int> billingType { get; set; }
        public string HospitalBillingClass { get; set; }
        public string pensionNumber { get; set; }
        public Nullable<int> MRN_Feed { get; set; }
        public System.DateTime dateTimeStart { get; set; }
        public int booking_ID { get; set; }
        public System.DateTime BookingStartedOn { get; set; }
        public System.DateTime dateTimeEnd { get; set; }
        public int duration { get; set; }
        public string type { get; set; }
        public Nullable<int> location_ID { get; set; }
        public Nullable<int> room_ID { get; set; }
        public Nullable<byte> PaymentClass { get; set; }
        public string PaymentClassUserUpdated { get; set; }
        public Nullable<System.DateTime> PaymentClassDateUpdated { get; set; }
        public Nullable<long> ClinicalRecordId { get; set; }
        public string title { get; set; }
    }
}
