//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralLedgerTier
    {
        public GeneralLedgerTier()
        {
            this.GeneralLedgers = new HashSet<GeneralLedger>();
            this.ProductImportGeneralLedgerCodes = new HashSet<ProductImportGeneralLedgerCode>();
        }
    
        public int TierId { get; set; }
        public int Tier { get; set; }
        public string Name { get; set; }
        public int SettingId { get; set; }
        public bool Mandatory { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int LedgerType { get; set; }
    
        public virtual GlcSetting GlcSetting { get; set; }
        public virtual GeneralLedgerType GeneralLedgerType { get; set; }
        public virtual ICollection<GeneralLedger> GeneralLedgers { get; set; }
        public virtual ICollection<ProductImportGeneralLedgerCode> ProductImportGeneralLedgerCodes { get; set; }
    }
}
