//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlcSetting
    {
        public GlcSetting()
        {
            this.GeneralLedgerTiers = new HashSet<GeneralLedgerTier>();
        }
    
        public int SettingId { get; set; }
        public string Name { get; set; }
        public string FillCharacter { get; set; }
        public int Length { get; set; }
        public GlcFormat Format { get; set; }
    
        public virtual ICollection<GeneralLedgerTier> GeneralLedgerTiers { get; set; }
    }
}
