//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTrackConsumption
    {
        public int UsedId { get; set; }
        public int ProductId { get; set; }
        public string SPC { get; set; }
        public string LPC { get; set; }
        public string ScanCode { get; set; }
        public string Name { get; set; }
        public string LotNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<short> Quantity { get; set; }
        public string RebateCode { get; set; }
        public Nullable<int> Location { get; set; }
        public string LocationName { get; set; }
        public string PatientMRN { get; set; }
        public Nullable<long> ContainerId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string ClinicalGroup { get; set; }
        public string ClinicalSubGroup { get; set; }
        public string Manufacturer { get; set; }
        public string GL { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string BuyCurrency { get; set; }
        public Nullable<double> BuyCurrencyRate { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string userCreated { get; set; }
        public Nullable<HMS.HealthTrack.Web.Data.Model.ConsumptionProcessingStatus> ProcessingStatus { get; set; }
        public string ProcessingStatusMessage { get; set; }
        public Nullable<bool> Reported { get; set; }
        public string ReportedBy { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<System.DateTime> ConsumedOn { get; set; }
        public Nullable<int> InventoryProductId { get; set; }
        public string PaymentClass { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
    }
}
