//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTrackLocation
    {
        public int location_ID { get; set; }
        public string name { get; set; }
        public string shortName { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
