//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryContext : DbContext
    {
        public InventoryContext()
            : base("name=InventoryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Company> Companies { get; set; }
        public virtual IDbSet<Property> Properties { get; set; }
        public virtual IDbSet<OrderItem> OrderItems { get; set; }
        public virtual IDbSet<Address> Addresses { get; set; }
        public virtual IDbSet<Category> Categories { get; set; }
        public virtual IDbSet<ExternalProductMapping> ExternalProductMappings { get; set; }
        public virtual IDbSet<StockLocation> StockLocations { get; set; }
        public virtual IDbSet<OraclePurchaseOrderError> OraclePurchaseOrderErrors { get; set; }
        public virtual IDbSet<OraclePurchaseOrderReceipt> OraclePurchaseOrderReceipts { get; set; }
        public virtual IDbSet<PriceType> PriceTypes { get; set; }
        public virtual IDbSet<ProductPrice> ProductPrices { get; set; }
        public virtual IDbSet<ProductStockRequest> ProductStockRequests { get; set; }
        public virtual IDbSet<StockSet> StockSets { get; set; }
        public virtual IDbSet<Order> Orders { get; set; }
        public virtual IDbSet<Product> Products { get; set; }
        public virtual IDbSet<Stock> Stocks { get; set; }
        public virtual IDbSet<StockSetItem> StockSetItems { get; set; }
        public virtual IDbSet<OrderItemSource> OrderItemSources { get; set; }
        public virtual IDbSet<AddressCorporate> AddressCorporates { get; set; }
        public virtual IDbSet<Supplier> Suppliers { get; set; }
        public virtual IDbSet<StockSetting> StockSettings { get; set; }
        public virtual IDbSet<Manufacturer> Manufacturers { get; set; }
        public virtual IDbSet<UserPreference> UserPreferences { get; set; }
        public virtual IDbSet<StockTake> StockTakes { get; set; }
        public virtual IDbSet<StockTakeItem> StockTakeItems { get; set; }
        public virtual IDbSet<DashboardNotification> DashboardNotifications { get; set; }
        public virtual IDbSet<GeneralLedger> GeneralLedgers { get; set; }
        public virtual IDbSet<GeneralLedgerTier> GeneralLedgerTiers { get; set; }
        public virtual IDbSet<GlcSetting> GlcSettings { get; set; }
        public virtual IDbSet<GeneralLedgerClosure> GeneralLedgerClosures { get; set; }
        public virtual IDbSet<GeneralLedgerClosureRoot> GeneralLedgerClosureRoots { get; set; }
        public virtual IDbSet<ClinicalConsumption> ClinicalConsumptions { get; set; }
        public virtual IDbSet<CategoryClosure> CategoryClosures { get; set; }
        public virtual IDbSet<CategoryClosureRoot> CategoryClosureRoots { get; set; }
        public virtual IDbSet<ProductCategory> ProductCategories { get; set; }
        public virtual IDbSet<GeneralLedgerType> GeneralLedgerTypes { get; set; }
        public virtual IDbSet<ProductImport> ProductImports { get; set; }
        public virtual IDbSet<HealthTrackLocation> HealthTrackLocations { get; set; }
        public virtual IDbSet<StockLocationMapping> StockLocationMappings { get; set; }
        public virtual IDbSet<ExternalMappedCategory> ExternalMappedCategories { get; set; }
        public virtual IDbSet<ConsumptionNotificationManagement> ConsumptionNotificationManagements { get; set; }
        public virtual IDbSet<ProductsWithConsumptionForExport> ProductsWithConsumptionForExports { get; set; }
        public virtual IDbSet<ProductImportGeneralLedgerCode> ProductImportGeneralLedgerCodes { get; set; }
        public virtual IDbSet<ProductImportData> ProductImportDatas { get; set; }
        public virtual IDbSet<HealthTrackProductMapping> HealthTrackProductMappings { get; set; }
        public virtual IDbSet<UnmanagedConsumption> UnmanagedConsumptions { get; set; }
        public virtual IDbSet<HealthTrackConsumption> HealthTrackConsumptions { get; set; }
        public virtual IDbSet<PaymentClassMapping> PaymentClassMappings { get; set; }
        public virtual IDbSet<NegativeStock> NegativeStocks { get; set; }
        public virtual IDbSet<MedicareCategory> MedicareCategories { get; set; }
        public virtual IDbSet<MedicareGroup> MedicareGroups { get; set; }
        public virtual IDbSet<MedicareProduct> MedicareProducts { get; set; }
        public virtual IDbSet<MedicareProductSponsor> MedicareProductSponsors { get; set; }
        public virtual IDbSet<MedicareSubGroup> MedicareSubGroups { get; set; }
        public virtual IDbSet<StockAdjustment> StockAdjustments { get; set; }
        public virtual IDbSet<StockAdjustmentReason> StockAdjustmentReasons { get; set; }
        public virtual IDbSet<DeductionRequiringPaymentClass> DeductionsRequiringPaymentClass { get; set; }
        public virtual IDbSet<StockAdjustmentStock> StockAdjustmentStocks { get; set; }
        public virtual IDbSet<ScanCode> ScanCodes { get; set; }
        public virtual IDbSet<OrderChannel> OrderChannels { get; set; }
        public virtual IDbSet<OrderChannelLocation> OrderChannelLocations { get; set; }
        public virtual IDbSet<OrderChannelProduct> OrderChannelProducts { get; set; }
        public virtual IDbSet<Submission> Submissions { get; set; }
        public virtual IDbSet<Consumption> Consumptions { get; set; }
        public virtual IDbSet<ConsumptionReversal> ConsumptionReversals { get; set; }
        public virtual IDbSet<ConsumptionManagement> ConsumptionManagements { get; set; }
    }
}
