//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Api.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Master
    {
        public Inventory_Master()
        {
            this.Inventory_Used = new HashSet<ConsumptionNotification>();
        }
    
        public int Inv_ID { get; set; }
        public string Inv_SPC { get; set; }
        public string Inv_LPC { get; set; }
        public string Inv_UPN { get; set; }
        public string Inv_Description { get; set; }
        public string Inv_Group { get; set; }
        public string Inv_SubGroup { get; set; }
        public Nullable<decimal> Inv_BuyPrice { get; set; }
        public string Inv_BuyCurrency { get; set; }
        public Nullable<double> Inv_BuyCurrencyRate { get; set; }
        public Nullable<decimal> Inv_SellPrice { get; set; }
        public string Inv_GL { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<bool> Inv_UseExpired { get; set; }
        public Nullable<bool> Inv_UseSterile { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public string userLastModified { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string userCreated { get; set; }
        public string Billing_Code { get; set; }
        public Nullable<decimal> Min_Benefit { get; set; }
        public Nullable<decimal> Max_Benefit { get; set; }
        public string Description_Additional { get; set; }
        public int Max_Uses { get; set; }
        public string Dimensions { get; set; }
        public string ProductModel { get; set; }
        public string SpecialRequirements { get; set; }
        public Nullable<int> Markup { get; set; }
        public Nullable<int> PriceModelID { get; set; }
    
        public virtual ICollection<ConsumptionNotification> Inventory_Used { get; set; }
    }
}
