
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public interface IDbContextInventoryContext : IObjectContextAdapter 
    {
        IDbSet<Company> Companies { get; set; }
        IDbSet<Property> Properties { get; set; }
        IDbSet<OrderItem> OrderItems { get; set; }
        IDbSet<Address> Addresses { get; set; }
        IDbSet<Category> Categories { get; set; }
        IDbSet<ExternalProductMapping> ExternalProductMappings { get; set; }
        IDbSet<StockLocation> StockLocations { get; set; }
        IDbSet<OraclePurchaseOrderError> OraclePurchaseOrderErrors { get; set; }
        IDbSet<OraclePurchaseOrderReceipt> OraclePurchaseOrderReceipts { get; set; }
        IDbSet<PriceType> PriceTypes { get; set; }
        IDbSet<ProductPrice> ProductPrices { get; set; }
        IDbSet<ProductStockRequest> ProductStockRequests { get; set; }
        IDbSet<StockSet> StockSets { get; set; }
        IDbSet<Order> Orders { get; set; }
        IDbSet<Product> Products { get; set; }
        IDbSet<Stock> Stocks { get; set; }
        IDbSet<StockSetItem> StockSetItems { get; set; }
        IDbSet<OrderItemSource> OrderItemSources { get; set; }
        IDbSet<AddressCorporate> AddressCorporates { get; set; }
        IDbSet<Supplier> Suppliers { get; set; }
        IDbSet<StockSetting> StockSettings { get; set; }
        IDbSet<Manufacturer> Manufacturers { get; set; }
        IDbSet<UserPreference> UserPreferences { get; set; }
        IDbSet<StockTake> StockTakes { get; set; }
        IDbSet<StockTakeItem> StockTakeItems { get; set; }
        IDbSet<DashboardNotification> DashboardNotifications { get; set; }
        IDbSet<GeneralLedger> GeneralLedgers { get; set; }
        IDbSet<GeneralLedgerTier> GeneralLedgerTiers { get; set; }
        IDbSet<GlcSetting> GlcSettings { get; set; }
        IDbSet<GeneralLedgerClosure> GeneralLedgerClosures { get; set; }
        IDbSet<GeneralLedgerClosureRoot> GeneralLedgerClosureRoots { get; set; }
        IDbSet<ClinicalConsumption> ClinicalConsumptions { get; set; }
        IDbSet<CategoryClosure> CategoryClosures { get; set; }
        IDbSet<CategoryClosureRoot> CategoryClosureRoots { get; set; }
        IDbSet<ProductCategory> ProductCategories { get; set; }
        IDbSet<GeneralLedgerType> GeneralLedgerTypes { get; set; }
        IDbSet<ProductImport> ProductImports { get; set; }
        IDbSet<HealthTrackLocation> HealthTrackLocations { get; set; }
        IDbSet<StockLocationMapping> StockLocationMappings { get; set; }
        IDbSet<ExternalMappedCategory> ExternalMappedCategories { get; set; }
        IDbSet<ConsumptionNotificationManagement> ConsumptionNotificationManagements { get; set; }
        IDbSet<ProductsWithConsumptionForExport> ProductsWithConsumptionForExports { get; set; }
        IDbSet<ProductImportGeneralLedgerCode> ProductImportGeneralLedgerCodes { get; set; }
        IDbSet<ProductImportData> ProductImportDatas { get; set; }
        IDbSet<HealthTrackProductMapping> HealthTrackProductMappings { get; set; }
        IDbSet<UnmanagedConsumption> UnmanagedConsumptions { get; set; }
        IDbSet<HealthTrackConsumption> HealthTrackConsumptions { get; set; }
        IDbSet<PaymentClassMapping> PaymentClassMappings { get; set; }
        IDbSet<NegativeStock> NegativeStocks { get; set; }
        IDbSet<MedicareCategory> MedicareCategories { get; set; }
        IDbSet<MedicareGroup> MedicareGroups { get; set; }
        IDbSet<MedicareProduct> MedicareProducts { get; set; }
        IDbSet<MedicareProductSponsor> MedicareProductSponsors { get; set; }
        IDbSet<MedicareSubGroup> MedicareSubGroups { get; set; }
        IDbSet<StockAdjustment> StockAdjustments { get; set; }
        IDbSet<StockAdjustmentReason> StockAdjustmentReasons { get; set; }
        IDbSet<DeductionRequiringPaymentClass> DeductionsRequiringPaymentClass { get; set; }
        IDbSet<StockAdjustmentStock> StockAdjustmentStocks { get; set; }
        IDbSet<ScanCode> ScanCodes { get; set; }
        IDbSet<OrderChannel> OrderChannels { get; set; }
        IDbSet<OrderChannelLocation> OrderChannelLocations { get; set; }
        IDbSet<OrderChannelProduct> OrderChannelProducts { get; set; }
        IDbSet<Submission> Submissions { get; set; }
        IDbSet<Consumption> Consumptions { get; set; }
        IDbSet<ConsumptionReversal> ConsumptionReversals { get; set; }
        IDbSet<ConsumptionManagement> ConsumptionManagements { get; set; }
        DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
    
    }
}
