//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareCategory
    {
        public MedicareCategory()
        {
            this.MedicareGroups = new HashSet<MedicareGroup>();
        }
    
        public int MedicareCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MedicareGroup> MedicareGroups { get; set; }
    }
}
