//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareGroup
    {
        public MedicareGroup()
        {
            this.MedicareProducts = new HashSet<MedicareProduct>();
            this.MedicareSubGroups = new HashSet<MedicareSubGroup>();
        }
    
        public int MedicareGroupId { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> MedicareCategoryId { get; set; }
    
        public virtual MedicareCategory MedicareCategory { get; set; }
        public virtual ICollection<MedicareProduct> MedicareProducts { get; set; }
        public virtual ICollection<MedicareSubGroup> MedicareSubGroups { get; set; }
    }
}
