//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareSubGroup
    {
        public MedicareSubGroup()
        {
            this.MedicareProducts = new HashSet<MedicareProduct>();
        }
    
        public int MedicareSubGroupId { get; set; }
        public int MedicareGroupId { get; set; }
        public string Name { get; set; }
    
        public virtual MedicareGroup MedicareGroup { get; set; }
        public virtual ICollection<MedicareProduct> MedicareProducts { get; set; }
    }
}
