//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareProductSponsor
    {
        public MedicareProductSponsor()
        {
            this.MedicareProducts = new HashSet<MedicareProduct>();
        }
    
        public string Code { get; set; }
        public int company_ID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<MedicareProduct> MedicareProducts { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
