//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OraclePurchaseOrderError
    {
        public int PurchaseOrderErrorId { get; set; }
        public long InventoryOrderId { get; set; }
        public long InventoryOrderItemId { get; set; }
        public string ItemDescription { get; set; }
        public long RequestId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ProcessFlag { get; set; }
        public string InterfaceSourceCode { get; set; }
    }
}
