//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OraclePurchaseOrderReceipt
    {
        public int PurchaseOrderReceiptId { get; set; }
        public long InventoryOrderId { get; set; }
        public long InventoryOrderItemId { get; set; }
        public long OracleRequisitionNumber { get; set; }
        public long OracleRequisitionLineNumber { get; set; }
        public long OracleRequisitionDistributionNumber { get; set; }
        public string OracleDistribution { get; set; }
        public long OracleVendorCode { get; set; }
        public string OracleSupplierProductCode { get; set; }
        public string OracleHospitalProductCode { get; set; }
        public double OraclePricePerUnit { get; set; }
        public string OracleUnitOfMeasure { get; set; }
        public string OracleOrgId { get; set; }
    }
}
