//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    
    public enum OrderSubmissionStatus : int
    {
        Unknown = 0,
        NotApplicable = 1,
        AwaitingSubmission = 2,
        Submitted = 3,
        Success = 4,
        InError = 5
    }
}
