//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemSource
    {
        public int ItemSourceId { get; set; }
        public int OrderItemId { get; set; }
        public Nullable<int> StockRequestId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> invUsed_ID { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual ProductStockRequest ProductStockRequest { get; set; }
        public virtual ConsumptionNotificationManagement ConsumptionNotificationManagement { get; set; }
    }
}
