//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderItemSources = new HashSet<OrderItemSource>();
            this.ConsumptionNotificationManagements = new HashSet<ConsumptionNotificationManagement>();
            this.StockAdjustments = new HashSet<StockAdjustment>();
            this.ConsumptionManagements = new HashSet<ConsumptionManagement>();
        }
    
        public int OrderItemId { get; set; }
        public int InventoryOrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool IncludeRebateCode { get; set; }
        public Nullable<HMS.HealthTrack.Web.Data.Model.Inventory.OrderItemStatus> Status { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderItemSource> OrderItemSources { get; set; }
        public virtual ICollection<ConsumptionNotificationManagement> ConsumptionNotificationManagements { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustments { get; set; }
        public virtual ICollection<ConsumptionManagement> ConsumptionManagements { get; set; }
    }
}
