//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChannel
    {
        public OrderChannel()
        {
            this.OrderChannelLocations = new HashSet<OrderChannelLocation>();
            this.OrderChannelProducts = new HashSet<OrderChannelProduct>();
            this.Submissions = new HashSet<Submission>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int OrderChannelId { get; set; }
        public string Name { get; set; }
        public string Reference { get; set; }
        public Nullable<int> OrganisationId { get; set; }
    
        public virtual ICollection<OrderChannelLocation> OrderChannelLocations { get; set; }
        public virtual ICollection<OrderChannelProduct> OrderChannelProducts { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
