//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChannelProduct
    {
        public int OrderChannelProductId { get; set; }
        public int OrderChannelId { get; set; }
        public int ProductId { get; set; }
        public string Reference { get; set; }
        public bool AutomaticOrder { get; set; }
    
        public virtual OrderChannel OrderChannel { get; set; }
        public virtual Product Product { get; set; }
    }
}
