//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceType
    {
        public PriceType()
        {
            this.ProductPrices = new HashSet<ProductPrice>();
            this.PaymentClassMappings = new HashSet<PaymentClassMapping>();
        }
    
        public int PriceTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<PaymentClassMapping> PaymentClassMappings { get; set; }
    }
}
