//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int PriceId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string BuyCurrency { get; set; }
        public string BuyCurrencyRate { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public int PriceTypeId { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual Product Product { get; set; }
    }
}
