//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImportGeneralLedgerCode
    {
        public int ProductImportId { get; set; }
        public int TierId { get; set; }
        public string Code { get; set; }
    
        public virtual GeneralLedgerTier GeneralLedgerTier { get; set; }
        public virtual ProductImport ProductImport { get; set; }
    }
}
