//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ExternalProductMappings = new HashSet<ExternalProductMapping>();
            this.OrderItems = new HashSet<OrderItem>();
            this.Prices = new HashSet<ProductPrice>();
            this.StockRequests = new HashSet<ProductStockRequest>();
            this.Stocks = new HashSet<Stock>();
            this.StockSetItems = new HashSet<StockSetItem>();
            this.ProductSettings = new HashSet<StockSetting>();
            this.StockTakeItems = new HashSet<StockTakeItem>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductImports = new HashSet<ProductImport>();
            this.ScanCodes = new HashSet<ScanCode>();
            this.OrderChannelProducts = new HashSet<OrderChannelProduct>();
        }
    
        public int ProductId { get; set; }
        public string SPC { get; set; }
        public string LPC { get; set; }
        public string Description { get; set; }
        public string GLC { get; set; }
        public string Manufacturer { get; set; }
        public bool UseExpired { get; set; }
        public bool UseSterile { get; set; }
        public int MaxUses { get; set; }
        public string Notes { get; set; }
        public string SpecialRequirements { get; set; }
        public Nullable<int> PrimarySupplier { get; set; }
        public Nullable<int> SecondarySupplier { get; set; }
        public bool IsConsignment { get; set; }
        public Nullable<int> PriceModelId { get; set; }
        public string RebateCode { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string BuyCurrency { get; set; }
        public string BuyCurrencyRate { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> MarkUp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int MinimumOrder { get; set; }
        public int OrderMultiple { get; set; }
        public Nullable<int> ReorderThreshold { get; set; }
        public Nullable<int> TargetStockLevel { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public bool UseCategorySettings { get; set; }
        public bool UsePaymentClassPrice { get; set; }
        public ProductStatus ProductStatus { get; set; }
        public HMS.HealthTrack.Web.Data.Model.Inventory.ReorderSettings AutoReorderSetting { get; set; }
        public bool InError { get; set; }
        public bool ManageStock { get; set; }
        public Nullable<System.DateTime> ReplaceAfter { get; set; }
    
        public virtual Company PrimarySupplierCompany { get; set; }
        public virtual Company SecondarySupplierCompany { get; set; }
        public virtual ICollection<ExternalProductMapping> ExternalProductMappings { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<ProductPrice> Prices { get; set; }
        public virtual ICollection<ProductStockRequest> StockRequests { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<StockSetItem> StockSetItems { get; set; }
        public virtual ICollection<StockSetting> ProductSettings { get; set; }
        public virtual ICollection<StockTakeItem> StockTakeItems { get; set; }
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<ProductImport> ProductImports { get; set; }
        public virtual ICollection<ScanCode> ScanCodes { get; set; }
        public virtual ICollection<OrderChannelProduct> OrderChannelProducts { get; set; }
    }
}
