//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockRequest
    {
        public ProductStockRequest()
        {
            this.OrderItemSources = new HashSet<OrderItemSource>();
        }
    
        public int StockRequestId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public RequestStatus RequestStatus { get; set; }
        public bool Fulfilled { get; set; }
        public Nullable<int> RequestLocationId { get; set; }
        public bool IsUrgent { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public int RequestedQuantity { get; set; }
        public Nullable<int> ApprovedQuantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StockLocation Location { get; set; }
        public virtual ICollection<OrderItemSource> OrderItemSources { get; set; }
    }
}
