//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeItem
    {
        public StockTakeItem()
        {
            this.StockAdjustments = new HashSet<StockAdjustment>();
        }
    
        public int StockTakeItemId { get; set; }
        public int StockTakeId { get; set; }
        public int ProductId { get; set; }
        public StockTakeItemStatus Status { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> StockLevel { get; set; }
        public Nullable<int> PreviousStockLevel { get; set; }
        public Nullable<int> NewStockLevel { get; set; }
        public Nullable<int> Adjustment { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StockTake StockTake { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustments { get; set; }
    }
}
