//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public StockLocation()
        {
            this.Orders = new HashSet<Order>();
            this.Stocks = new HashSet<Stock>();
            this.ProductStockRequests = new HashSet<ProductStockRequest>();
            this.UserPreferences = new HashSet<UserPreference>();
            this.StockTakes = new HashSet<StockTake>();
            this.StockLocationMappings = new HashSet<StockLocationMapping>();
            this.OrderChannelLocations = new HashSet<OrderChannelLocation>();
        }
    
        public int LocationId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedUser { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> AddressId { get; set; }
        public byte[] LogoImage { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<ProductStockRequest> ProductStockRequests { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
        public virtual ICollection<StockTake> StockTakes { get; set; }
        public virtual ICollection<StockLocationMapping> StockLocationMappings { get; set; }
        public virtual ICollection<OrderChannelLocation> OrderChannelLocations { get; set; }
    }
}
