//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustmentStock
    {
        public long StockAdjustmentId { get; set; }
        public long StockId { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual StockAdjustment StockAdjustment { get; set; }
    }
}
