//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.StockAdjustmentStocks = new HashSet<StockAdjustmentStock>();
        }
    
        public long StockId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> BoughtPrice { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public string DeletionReason { get; set; }
        public StockStatus StockStatus { get; set; }
        public Nullable<int> Owner { get; set; }
        public int StoredAt { get; set; }
        public Nullable<int> PriceModelOnReceipt { get; set; }
        public Nullable<decimal> TaxRateOnReceipt { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public int ReceivedQuantity { get; set; }
        public bool IsNegative { get; set; }
    
        public virtual StockLocation StorageLocation { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<StockAdjustmentStock> StockAdjustmentStocks { get; set; }
    }
}
