//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public StockAdjustment()
        {
            this.StockAdjustmentStocks = new HashSet<StockAdjustmentStock>();
        }
    
        public long StockAdjustmentId { get; set; }
        public Nullable<System.DateTime> AdjustedOn { get; set; }
        public string AdjustedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public string DeletionReason { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<long> ClinicalRecordId { get; set; }
        public AdjustmentSource Source { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> GeneralLedgerId { get; set; }
        public string Note { get; set; }
        public Nullable<int> StockTakeItemId { get; set; }
        public Nullable<int> StockAdjustmentReasonId { get; set; }
        public bool IsPositive { get; set; }
        public Nullable<int> OrderItemId { get; set; }
    
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual StockAdjustmentReason StockAdjustmentReason { get; set; }
        public virtual StockTakeItem StockTakeItem { get; set; }
        public virtual ICollection<StockAdjustmentStock> StockAdjustmentStocks { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
