//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionId { get; set; }
        public int OrderId { get; set; }
        public int OrderChannelId { get; set; }
        public string SubmissionReference { get; set; }
        public SubmissionStatus SubmissionStatus { get; set; }
        public string TriggeredBy { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string AdditionalDetails { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderChannel OrderChannel { get; set; }
    }
}
