//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnmanagedConsumption
    {
        public int invUsed_ID { get; set; }
        public Nullable<long> container_ID { get; set; }
        public Nullable<byte> cversion { get; set; }
        public Nullable<int> patient_ID { get; set; }
        public Nullable<int> invItem_ID { get; set; }
        public string invUsed_SPC { get; set; }
        public string invUsed_LPC { get; set; }
        public Nullable<decimal> invUsed_SellPrice { get; set; }
        public string invUsed_GL { get; set; }
        public string invUsed_SerialNo { get; set; }
        public Nullable<short> invUsed_Qty { get; set; }
        public string invUsed_Units { get; set; }
        public Nullable<int> invUsed_Location { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public string userLastModified { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string userCreated { get; set; }
        public Nullable<int> admissionStage_ID { get; set; }
        public string invDescription { get; set; }
        public Nullable<bool> invNotUsed { get; set; }
        public int StockStatus { get; set; }
        public string StatusMessage { get; set; }
        public string LOTNO { get; set; }
        public string ExtStudy_ID { get; set; }
    }
}
