//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_ID { get; set; }
        public Nullable<int> patient_ID { get; set; }
        public System.DateTime dateTimeStart { get; set; }
        public System.DateTime dateTimeEnd { get; set; }
        public int duration { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<int> resource_ID { get; set; }
        public Nullable<int> location_ID { get; set; }
        public Nullable<int> room_ID { get; set; }
        public Nullable<int> drIDBooked { get; set; }
        public Nullable<int> drIDActual { get; set; }
        public Nullable<int> referral_ID { get; set; }
        public Nullable<int> note_ID { get; set; }
        public Nullable<int> bookingPriority { get; set; }
        public Nullable<System.DateTime> dateTimePreviousBooking { get; set; }
        public Nullable<System.DateTime> dateTimeConfirmed { get; set; }
        public Nullable<System.DateTime> dateTimeArrived { get; set; }
        public Nullable<System.DateTime> dateTimeInSession { get; set; }
        public Nullable<System.DateTime> dateTimeOutSession { get; set; }
        public Nullable<System.DateTime> dateTimeClosed { get; set; }
        public Nullable<System.DateTime> dateTimeSeen { get; set; }
        public Nullable<System.DateTime> dateTimeCompleted { get; set; }
        public Nullable<int> cntBookingChange { get; set; }
        public string userCreated { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string userLastModified { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public string rcIdentifier1 { get; set; }
        public Nullable<int> rcIdentifier2 { get; set; }
        public byte[] ctimestamp { get; set; }
        public bool unregistered { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string contactNumber { get; set; }
        public byte category { get; set; }
        public bool isFirstBooking { get; set; }
        public Nullable<int> lastInvoiceID { get; set; }
        public Nullable<int> programAttachedTo { get; set; }
        public bool inpatientBooking { get; set; }
        public string inpatientWard { get; set; }
        public byte availableToExternal { get; set; }
        public Nullable<int> Transport { get; set; }
        public Nullable<System.DateTime> TransportDate { get; set; }
        public Nullable<int> BillLocation_ID { get; set; }
        public Nullable<int> ProvNum_ID { get; set; }
        public Nullable<byte> BillTo { get; set; }
        public Nullable<int> BillingType { get; set; }
        public string HospitalBillingClass { get; set; }
        public bool PublishToRepository { get; set; }
        public Nullable<int> Associate { get; set; }
        public string TriageType { get; set; }
        public Nullable<long> TriageOptions { get; set; }
        public string FollowUpDetails { get; set; }
        public bool PreventSMSReminder { get; set; }
        public string userConfirmed { get; set; }
        public string userArrived { get; set; }
        public string userInSession { get; set; }
        public string userOutSession { get; set; }
        public string userClosed { get; set; }
        public Nullable<int> Link_ID { get; set; }
        public Nullable<int> Admission_ID { get; set; }
        public bool Urgent { get; set; }
        public bool RequestEarlier { get; set; }
        public string DeletionReason { get; set; }
        public Nullable<int> QuoteNo { get; set; }
        public Nullable<byte> PaymentClass { get; set; }
        public string PaymentClassUserUpdated { get; set; }
        public Nullable<System.DateTime> PaymentClassDateUpdated { get; set; }
        public Nullable<int> SelectedStaff1 { get; set; }
        public Nullable<int> SelectedStaff2 { get; set; }
        public Nullable<int> SelectedStaff3 { get; set; }
        public Nullable<int> SelectedStaff4 { get; set; }
        public Nullable<System.DateTime> DateTimeNoShowed { get; set; }
        public string UserNoShowed { get; set; }
        public Nullable<byte> SelectedDeletionReason { get; set; }
    
        public virtual Booking Booking1 { get; set; }
        public virtual Booking Booking2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
