//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFeed
    {
        public ExternalFeed()
        {
            this.PatientMappings = new HashSet<PatientMapping>();
        }
    
        public int feed_ID { get; set; }
        public Nullable<int> service_Category { get; set; }
        public string service_Name { get; set; }
        public int service_ID { get; set; }
        public int feed_Type { get; set; }
        public string feed_InDirectory { get; set; }
        public string feed_OutDirectory { get; set; }
        public string feed_OutHostname { get; set; }
        public Nullable<int> feed_OutPort { get; set; }
        public Nullable<int> location_ID { get; set; }
        public Nullable<int> doctor_ID { get; set; }
        public bool embedded_Files { get; set; }
        public Nullable<int> feed_Provider { get; set; }
        public bool feed_Enabled { get; set; }
        public bool requestForm_Enabled { get; set; }
        public string feed_BackupDirectory { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string modifiedUser { get; set; }
        public string requestForm { get; set; }
        public Nullable<System.DateTime> lastActivityDateTime { get; set; }
        public Nullable<System.DateTime> lastWarningDateTime { get; set; }
        public bool warnOperatorIfNoActivity { get; set; }
        public Nullable<int> warnThresholdHours { get; set; }
        public Nullable<int> warnHoursBetweenWarnings { get; set; }
        public Nullable<byte> warnStartHour { get; set; }
        public Nullable<byte> warnStopHour { get; set; }
        public string warnEmailAddresses { get; set; }
        public string SynopsisPrefix { get; set; }
        public Nullable<int> d_type { get; set; }
        public string OnPatientFind { get; set; }
        public string OnPatientFindQuery { get; set; }
        public string OnClinicalRecord { get; set; }
        public string SQLConnectionString { get; set; }
        public string Feed_ReprocessDirectory { get; set; }
        public Nullable<int> MappingFeed_ID { get; set; }
        public bool UserDefined { get; set; }
        public bool Logging_Enabled { get; set; }
        public Nullable<int> KeepMessagesDays { get; set; }
        public string PreviewLOINCS { get; set; }
        public bool MRNPatientMatch { get; set; }
        public bool GenerateFillerCode { get; set; }
        public bool IgnoreSystemMatch { get; set; }
        public bool Disable_ClinicalRecordMove { get; set; }
        public bool SupportsHMSOrder { get; set; }
        public string AssigningAuthority { get; set; }
        public string OutboundAssigningAuthority { get; set; }
        public Nullable<int> GroupFeed_ID { get; set; }
        public bool HT_MRN { get; set; }
        public string FileLayout { get; set; }
        public bool DemographicsMRN { get; set; }
        public bool SupportsMultipleTestTypes { get; set; }
        public bool CanBeVerified { get; set; }
    
        public virtual ICollection<PatientMapping> PatientMappings { get; set; }
    }
}
