//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Core
    {
        public int List_ID { get; set; }
        public string ListGroup { get; set; }
        public string ListName { get; set; }
        public int ItemID { get; set; }
        public string ItemValue { get; set; }
        public bool Deleted { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
        public string AdditionalNotes { get; set; }
        public string Comment { get; set; }
        public bool DefaultItem { get; set; }
        public Nullable<int> HMS_ID { get; set; }
        public bool ModifiedBySite { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserDeleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public bool SystemItem { get; set; }
    }
}
