//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_Container
    {
        public long container_ID { get; set; }
        public byte cversion { get; set; }
        public int patient_ID { get; set; }
        public string groupBy { get; set; }
        public Nullable<int> booking_ID { get; set; }
        public Nullable<int> admission_ID { get; set; }
        public Nullable<int> episode { get; set; }
        public Nullable<int> d_status { get; set; }
        public string tableName { get; set; }
        public string formDisplay { get; set; }
        public Nullable<int> RecordSubCategory { get; set; }
        public Nullable<byte> dataSource { get; set; }
        public Nullable<byte> whoReported { get; set; }
        public string recordType { get; set; }
        public Nullable<byte> versionsCount { get; set; }
        public string userCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public string userLastModified { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public bool temporaryRecord { get; set; }
        public Nullable<int> note_ID { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> deletionReason { get; set; }
        public string deletionUser { get; set; }
        public Nullable<int> deletionNote { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public Nullable<bool> archive { get; set; }
        public Nullable<int> referral_ID { get; set; }
        public Nullable<bool> HasCurrentWorkflow { get; set; }
        public string securityKeyword { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> ReferringMO { get; set; }
        public string Ward { get; set; }
        public string Bed { get; set; }
        public Nullable<bool> InPatient { get; set; }
        public Nullable<int> Classification { get; set; }
        public string AdditionalInfo { get; set; }
        public bool DocumentAttached { get; set; }
        public string Assignee { get; set; }
        public string CapturedBy { get; set; }
        public string Originator { get; set; }
        public string OriginatorDisplayName { get; set; }
        public string originatorType { get; set; }
        public Nullable<int> originator_ID { get; set; }
        public string ApprovedBy { get; set; }
        public byte D_copies { get; set; }
        public bool D_attachments { get; set; }
        public string D_creatorToApprove { get; set; }
        public int D_priority { get; set; }
        public Nullable<System.DateTime> D_statusDate { get; set; }
        public Nullable<int> D_LastDocState { get; set; }
        public Nullable<System.DateTime> LastDocStateDate { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public string D_stateSet { get; set; }
        public string D_workflow { get; set; }
        public bool D_WorkflowComplete { get; set; }
        public bool AutomatedWorkflowHistoryAvailable { get; set; }
        public string ExtContainer_ID { get; set; }
        public Nullable<int> Feed_ID { get; set; }
        public bool HasClinicalAttachement { get; set; }
        public Nullable<System.DateTime> ProcedureEndDate { get; set; }
        public int BillLocation_ID { get; set; }
        public Nullable<int> ProvNum_ID { get; set; }
        public Nullable<byte> BillTo { get; set; }
        public Nullable<int> BillingType { get; set; }
        public string HospitalBillingClass { get; set; }
        public Nullable<int> TabUsage { get; set; }
        public bool NotForDistribution { get; set; }
        public string ByDateDescription { get; set; }
        public Nullable<System.DateTime> ExtMeasurementLoadDate { get; set; }
        public Nullable<int> ExtMeasurementCount { get; set; }
    
        public virtual MR_Container MR_Container1 { get; set; }
        public virtual MR_Container MR_Container2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
