//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Bookings = new HashSet<Booking>();
            this.MR_Container = new HashSet<MR_Container>();
            this.Patient1 = new HashSet<Patient>();
            this.HL7_PatientMapping = new HashSet<PatientMapping>();
        }
    
        public int patient_ID { get; set; }
        public Nullable<int> company_ID { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public string knownAs { get; set; }
        public string initials { get; set; }
        public string title { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string ethnicity { get; set; }
        public Nullable<int> family_ID { get; set; }
        public bool inFamily { get; set; }
        public bool HasAlias { get; set; }
        public string mrn { get; set; }
        public string occupation { get; set; }
        public Nullable<int> patientType { get; set; }
        public string homePhone { get; set; }
        public string workPhone { get; set; }
        public string mobile { get; set; }
        public string homeFax { get; set; }
        public string workFax { get; set; }
        public string email { get; set; }
        public string pStatus { get; set; }
        public Nullable<System.DateTime> dateDeceased { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string userCreated { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public string userLastModified { get; set; }
        public Nullable<int> note_ID { get; set; }
        public string snd_name { get; set; }
        public Nullable<int> cntBookingNoShow { get; set; }
        public Nullable<int> cntBookingCancel { get; set; }
        public Nullable<int> cntBookingChange { get; set; }
        public string medicare { get; set; }
        public string medicareRefNo { get; set; }
        public Nullable<int> MediExpYYYY { get; set; }
        public Nullable<byte> MediExpMM { get; set; }
        public Nullable<System.DateTime> medicareVerifyDate { get; set; }
        public string vetAffairs { get; set; }
        public Nullable<int> healthFundID { get; set; }
        public string fundNumber { get; set; }
        public string fundNumberUPI { get; set; }
        public Nullable<int> fundExpYYYY { get; set; }
        public Nullable<byte> fundExpMM { get; set; }
        public Nullable<int> fundPlan { get; set; }
        public Nullable<int> feeTable_ID { get; set; }
        public Nullable<int> attendingMO { get; set; }
        public Nullable<int> primaryHealthProvider { get; set; }
        public Nullable<System.DateTime> lastVisitGP { get; set; }
        public Nullable<int> treatmentLocation { get; set; }
        public Nullable<bool> fullReg { get; set; }
        public Nullable<int> billingType { get; set; }
        public string HospitalBillingClass { get; set; }
        public Nullable<bool> privacyDisclaimer { get; set; }
        public Nullable<bool> archive { get; set; }
        public string pensionNumber { get; set; }
        public Nullable<System.DateTime> commenced { get; set; }
        public Nullable<System.DateTime> ceased { get; set; }
        public string userIdentifier1 { get; set; }
        public string userIdentifier2 { get; set; }
        public string extPatient_ID { get; set; }
        public bool possibleDuplicate { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> deletionReason { get; set; }
        public Nullable<int> deletionNote { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public string deletionUser { get; set; }
        public string jobtitle { get; set; }
        public Nullable<byte> primaryPhone { get; set; }
        public Nullable<System.DateTime> dateFirstBooking { get; set; }
        public Nullable<System.DateTime> dateFirstInvoice { get; set; }
        public bool alertBilling { get; set; }
        public bool alertPatientNote { get; set; }
        public byte alertUser1 { get; set; }
        public byte alertUser2 { get; set; }
        public byte[] ctimestamp { get; set; }
        public bool patientInfoForm { get; set; }
        public bool inpatient { get; set; }
        public string ward { get; set; }
        public Nullable<System.DateTime> dateLatestBooking { get; set; }
        public Nullable<System.DateTime> noStatementDate { get; set; }
        public string noStatementReason { get; set; }
        public Nullable<System.DateTime> accountHoldDate { get; set; }
        public string accountHoldReason { get; set; }
        public Nullable<System.DateTime> programLatestExpiryDate { get; set; }
        public bool chartDoNotMove { get; set; }
        public Nullable<System.DateTime> LastSuccessfulPVM { get; set; }
        public Nullable<System.DateTime> LastSuccessfulPVF { get; set; }
        public Nullable<System.DateTime> LastSuccessfulOVV { get; set; }
        public bool FamilyHistoryPresent { get; set; }
        public bool AllergiesPresent { get; set; }
        public Nullable<int> Transport { get; set; }
        public Nullable<int> MRN_Feed { get; set; }
        public short BirthOrder { get; set; }
        public bool AllowAutomatedSMS { get; set; }
        public string SurnameSoundex { get; set; }
        public string PreferredPhone { get; set; }
        public Nullable<int> DevicesNotRecorded { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<MR_Container> MR_Container { get; set; }
        public virtual ICollection<Patient> Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
        public virtual ICollection<PatientMapping> HL7_PatientMapping { get; set; }
    }
}
