//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Clinical
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMapping
    {
        public int Feed_ID { get; set; }
        public string RemotePatient_ID { get; set; }
        public string PatientIdentifierList { get; set; }
        public Nullable<int> LocalPatient_ID { get; set; }
        public bool Owner { get; set; }
        public string AssigningAuthority { get; set; }
        public string Medicare { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public short BirthOrder { get; set; }
        public string AddrStreet { get; set; }
        public string AddrCity { get; set; }
        public string AddrState { get; set; }
        public string AddrPostCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MessageCode { get; set; }
        public string TriggerEvent { get; set; }
        public bool SystemMatched { get; set; }
        public bool UserMatched { get; set; }
        public string Username { get; set; }
        public bool UserCannotMatch { get; set; }
        public Nullable<bool> PossibleDuplicate { get; set; }
        public bool Merged { get; set; }
        public short InErrorCode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
        public string DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ExternalFeed ExternalFeed { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
