//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.17.13.0 (NJsonSchema v9.10.50.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace Newtonsoft
{
   internal class Json
   {
      public static object JsonConvert { get; internal set; }

      internal class JsonSerializerSettings
      {
      }
   }
}