//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTrackGroup
    {
        public string base_ID { get; set; }
        public string member_ID { get; set; }
    }
}
