//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTrackPermission
    {
        public HealthTrackPermission()
        {
            this.HealthTrackAuthorisations = new HashSet<HealthTrackAuthorisation>();
        }
    
        public string Keyword { get; set; }
        public string Description { get; set; }
        public bool VisibleToEditor { get; set; }
        public bool EffectMenuItem { get; set; }
        public string SubGroup { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Licensed { get; set; }
        public bool AllowOverride { get; set; }
    
        public virtual ICollection<HealthTrackAuthorisation> HealthTrackAuthorisations { get; set; }
    }
}
