//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTrackAuthorisation
    {
        public string User_ID { get; set; }
        public string Keyword { get; set; }
        public bool KeyValue { get; set; }
        public int Location_ID { get; set; }
        public int Department { get; set; }
    
        public virtual HealthTrackPermission HealthTrackPermission { get; set; }
    }
}
