//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.HealthTrack.Web.Data.Model.Security
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Security : DbContext
    {
        public Security()
            : base("name=Security")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HealthTrackAuthorisation> HealthTrackAuthorisations { get; set; }
        public virtual DbSet<HealthTrackPermission> HealthTrackPermissions { get; set; }
        public virtual DbSet<HealthTrackUser> HealthTrackUsers { get; set; }
        public virtual DbSet<HealthTrackGroup> HealthTrackGroups { get; set; }
    }
}
