IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company' AND COLUMN_NAME = 'IsSupplier')
	ALTER TABLE Company
	DROP CONSTRAINT DF_Company_IsSupplier
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company' AND COLUMN_NAME = 'IsSupplier')
	ALTER TABLE Company
	DROP COLUMN IsSupplier
	GO